### PR TITLE
Fix Stickler errors.

### PR DESCRIPTION
**Pull request by tiagoit**
# The New Web (Responsive)

Copy of The New Web using responsive techniques.

### Technology

HTML, CSS, Bootstrap

### Authors

- **Tiffany Arellano** - [@yirano](https://github.com/yirano)
- **Tiago Ferreira** - [@ferreirati](https://github.com/ferreirati)

### Links

- **Assignment page** - [The Odin Project](https://www.theodinproject.com/courses/html5-and-css3/lessons/building-with-responsive-design)
- **Live** - [Github pages](https://ferreirati.github.io/mv-06-htmlcss-newweb/src)

### CODE REVIEW

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Amazing job :thumbsup: team @ferreirati and @yirano 
You have done a good job.
However you have a few minor but required changes to make before completing this project.
- [ ] Add a search icon to the right most side of the sub-nav bar.
- [ ] align 3 articles per row for ```Latest News``` section around ```768``` pixels
- [ ] align 3 articles per row for ```Latest Funding``` section around ```768``` pixels
- [ ] align 2 articles per row for ```Apps, Gear, Tech``` section around ```768``` pixels
- [ ] align 3 articles per row for ```Latest Deals``` section around ```768``` pixels

Please make those changes and submit for another review.

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great progress team :clap: . However, some changes weren't made as it should be. Check below :arrow_down: 

- Below 1030px, the page starts to have an horizontal scrolling effect. :pray:  fix it.

- The **search icon** is still missing :no_entry: . :pray:  fix it.

 ### that's it :relaxed: . when finished, kindly resubmit another code review request :pray:

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work team :clap: . You made all the necessary changes **except** one. Fixing the remaining two linter errors. :pray: fix them and resubmit another code review request :mag:

**Review by stratospherique — APPROVED** [review]
### All good :100: . You project is approved :heavy_check_mark:  and you can merge to master :+1: . Keep up the good work :muscle:

**Pull request merged**
